### ISSUE TITLE
Add samples "Hungryman" and "Spring SMTP Gateway"

### ISSUE THREAD

**Issue by trisberg** [vmware-tanzu/application-accelerator-samples#14]
Add "Hungryman" and "Spring SMTP Gateway" samples.

Tasks for each sample:

- Add/Change license file to MIT-0 license (same as in the root of this repo)
- Update paths to point to this repo

Notes for VMware contributors:

- see https://github.com/vmware-tanzu/application-accelerator-samples/blob/main/CONTRIBUTING.md
- must be member of `vmware-tanzu` org to avoid CLA issues - https://cla.vmware.com/employee
- sign commits 
    - To acknowledge the Developer Certificate of Origin (DCO), sign your commits by adding Signed-off-by: John Doe <john.doe@email.com> to the last line of each Git commit message. The e-mail address used to sign must match the e-mail address of the Git author. If you set your `user.name` and `user.email` git config values, you can sign your commit automatically with `git commit -s`.

**Comment by gm2552** [comment]
PRs for these changes.  Although the "main" branch is not being pulled into a specific accelerator (only branches), a LICENSE file has been added to the main branches.

https://github.com/sample-accelerators/hungryman/pull/2
https://github.com/sample-accelerators/hungryman/pull/1

https://github.com/sample-accelerators/spring-smtp-gateway/pull/5
https://github.com/sample-accelerators/spring-smtp-gateway/pull/4

@trisberg Please review.
