### ISSUE TITLE
[Enhancement Request] Steeltoe accelerators - project name validation to check for C# syntax

### ISSUE THREAD

**Issue by Mpluya** [vmware-tanzu/application-accelerator-samples#179]
While generating from either [weatherforecast-csharp](https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/weatherforecast-csharp) or [weatherforecast-steeltoe](https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/weatherforecast-steeltoe), one of the required params is an application name. 
<img width="569" alt="Screenshot 2023-01-26 at 4 13 57 PM" src="https://user-images.githubusercontent.com/13173260/214972258-85bbefb8-ee13-4c30-957b-254370325766.png">

Although defaulted to 'Sample', a user may modify this to a different value - e.g. weatherforecast-steeltoe. This application name affects the following generated files:

generated from weatherforecast-steeltoe accelerator:
- https://github.com/Mpluya/weatherforecast-steeltoe/blob/3d91ae3b32b94ada4cf337c41ed89e06d56d203c/WeatherForecast.cs#L1
- https://github.com/Mpluya/weatherforecast-steeltoe/blob/3d91ae3b32b94ada4cf337c41ed89e06d56d203c/Controllers/WeatherForecastController.cs#L3

These 2 cs files are syntactically incorrect to a C# compiler. 

This request is to either:
- add validation to the application name before generating accelerator artifacts
or 
- massage the application name input to be syntactically correct in C#

**Comment by TimHess** [comment]
@Mpluya did you experience any other characters breaking compilation? I added a transformation to turn the `-` to `_` in .cs files and any other substitutions should be trivial if needed

**Comment by Mpluya** [comment]
@TimHess no additional user provided variables break outside of the application name. Thank you for the enhancement.

**Comment by trisberg** [comment]
Closing since linked PR should have fixed this
