### ISSUE TITLE
C# samples' Swagger endpoints not found

### ISSUE THREAD

**Issue by ccheetham** [vmware-tanzu/application-accelerator-samples#55]
The C# deployed apps should respond to the endpoint`/swagger`, but instead return 404.

Errant apps:
* weatherforecast-csharp
* weatherforecast-steeltoe

**Comment by trisberg** [comment]
I wonder if this is due to the way the buildpack works? Running the image with Docker locally I see the same issue.

```
No webpage was found for the web address: http://localhost:8080/swagger
```
