### ISSUE TITLE
Some potential defects in spring-smtp-sample

### ISSUE THREAD

**Issue by kdvolder** [vmware-tanzu/application-accelerator-samples#63]
To get it going for use in intellij demo I had to change a few things.

- portforward in the Tiltfile is 1025 whereas the actual port seems to be 1026 (as per the [workload.yml](https://github.com/vmware-tanzu/application-accelerator-samples/blob/main/spring-smtp-gateway/smtp-gateway/config/workload.yaml#L26))
- the name of the gateway sub-project is wrong in Tiltfile. It is using `spring-smtp-gateway` throughout, but the actual name is just `smtp-gateway`. I had to basically do a search replace in there to fix it.
- the pod selectors in both Tiltfiles are wrong and needed to be changed to these:

```
k8s_resource('smtp-gateway', port_forwards=["1026:1026"],
    extra_pod_selectors=[{'carto.run/workload-name': 'smtp-gateway'}])

k8s_resource('smtp-sink', port_forwards=[],
    extra_pod_selectors=[{'carto.run/workload-name': 'smtp-sink'}])
```

I am not sure this is actually 100% correct too (maybe it selects too many pods, such as build pods, instead of just run pods). But what is in the file currently, selecting based on `serving.knative.dev/service` doesn't work at all. Presumably this is because of the workload type being `server` and `worker` and so they don't actually result in creation of any knative services (as a `web` type workload would do).

**Comment by gm2552** [comment]
You correct that there are no knative labels on this pod due to using the `server` workload type.  Adding `app.kubernetes.io/component=run` as a selector in addition to your change above should help alleviate the issue.

**Comment by gm2552** [comment]
@kdvolder Please review the changes in both Tilt files in the above PR.
