### ISSUE TITLE
Add option for storage class for the postgresql fragment

### ISSUE THREAD

**Issue by trisberg** [vmware-tanzu/application-accelerator-samples#78]
We should prompt for storage class name since that could vary by cluster and apply it to the `postgres.yaml` file

```
  storageClassName: standard
```

**Comment by trisberg** [comment]
We should also set the `monitorStorageClassName` property to the same storage class since "standard" is not always a configured storage class.

**Comment by vmware-jaret** [comment]
Linked PR will contain, along with the service binding, this improvement.
